a="s"*5
print(a)
print("hello",end=" ")
print("welcome")
print("check")
print("aaaa","hsgzhjgs","kshdkjhs",sep=",")
java=int(input("enter java marks"))
maths=input("enter maths marks")
geoghraphy=input("enter geography marks")
print("you ward secured",java,"marks in java",maths)#,"marks in maths",geography,"marks in geography")
print("you ward secured"+str(java)+"marks in java"+maths)
print("your ward secured %5d in java and %s in maths" %(java,maths))
print("your ward secured {0:5} in java and {1} in maths".format(java,maths))
print(123)
print(23456)
print("{0:5}".format(123))
print("%5d"%(23456))
